### ISSUE TITLE
Sensor state unknown

### ISSUE THREAD

**Issue by codebude** [Bouni/abfallplus#16]
I configured the component as described, but my sensors show state "Unbekannt" (unknown). 
There are not error notifications in HA. Is there a possibility to see some debug logs?

![Screenshot_2023-10-29-10-43-59-712_io homeassistant companion android-edit](https://github.com/Bouni/abfallplus/assets/2236234/1d085bb9-d3c7-477f-8d79-991f2685f492)

My config looks like:

```yaml
- platform: abfallplus
  name: Gelber Sack
  key: e5543a3e190cb8d91c645660ad60965f
  municipality: 3707
  street: 241756
  trash_ids: "695"
  pattern: müll
```

I assume that my sensor configs are valid, because I just ran parts of your Python Code in visual studio and saw that the ICS file could be downloaded and contains the trash dates.
